POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGViYmJiOGEwYWRlYzg3ZDFjMDVkYyIsInVzZXJuYW1lIjoieGVmcm9rIiwiaWF0IjoxNjUzNTMyNTEzfQ.UzA5Hlw6d1LXXwGM2ONDKzH9QhiKXhQ5Dc_rt0ZCK4U

{
  "content": "nota para eliminar",
  "important": true
}
###
// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGViYmJiOGEwYWRlYzg3ZDFjMDVkYyIsInVzZXJuYW1lIjoieGVmcm9rIiwiaWF0IjoxNjUzNTMyNTEzfQ.UzA5Hlw6d1LXXwGM2ONDKzH9QhiKXhQ5Dc_rt0ZCK4U
###
POST http://localhost:3001/api/notes
Content-Type: application/json
